spring:
  application:
    name: ielts-platform-backend
  
  # Server configuration
  server:
    port: 8080
    servlet:
      context-path: /
  
  # Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# Logging configuration
logging:
  level:
    com.ryan.ieltsplatform: DEBUG
    org.springframework: INFO
    org.springframework.boot: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# OpenAPI configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha
  info:
    title: IELTS Platform Backend API
    description: REST API for IELTS training platform
    version: 1.0.0
    contact:
      name: Ryan Ngo
      email: ryan@example.com

# gRPC configuration will be added in gRPC task
