apiVersion: v1
kind: Service
metadata:
  name: ielts-frontend
  namespace: ielts-frontend
  labels:
    app: ielts-frontend
    version: v1
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/api/health"
spec:
  type: ClusterIP
  selector: 
    app: ielts-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  sessionAffinity: None
