apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-creds
            key: access_key_id
            namespace: external-secrets
          secretAccessKeySecretRef:
            name: aws-creds
            key: secret_access_key
            namespace: external-secrets
