apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: your-dockerhub-user/ielts-frontend
    newName: your-dockerhub-user/ielts-frontend
    newTag: dev-001
